title: Zhixiang Huang's Homepage
page-top-title: Zhixiang Huang
top-section-bg-text: I'm completing my B.S. in Artificial Intelligence at Anhui University and will join Northwestern Polytechnical University this fall to pursue a Master's degree in Computer Science and Technology.
home-subtitle: Zhixiang Huang&ensp;|&ensp;黄致祥
copyright-text: '&copy; Zhixiang Huang 2023-2025. All Rights Reserved.'
